### ISSUE TITLE
License

### ISSUE THREAD

**Issue by samestep** [milahu/vite-plugin-tree-sitter#1]
Hello! This project looks cool; I stumbled across it through https://github.com/nshen/vite-plugin-wasm-pack/issues/6 while trying to figure out how to get Tree-sitter to play nice with Vite. Could you add a `LICENSE` (e.g. [MIT](https://opensource.org/licenses/MIT)) to allow people to use this project?

**Comment by milahu** [comment]
done, thanks : )
